import smtplib
import ssl
import csv
from email.message import EmailMessage
from urllib.parse import urlparse
from dotenv import load_dotenv
import os

load_dotenv()

SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = int(os.getenv("SMTP_PORT"))
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")

def load_sites_from_csv(csv_path):
    sites = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["Web Sitesi"] and row["IK E-posta"]:
                sites.append({
                    "site": row["Web Sitesi"],
                    "email": row["IK E-posta"]
                })
    return sites

def extract_firma_name(site_url):
    domain = urlparse(site_url).netloc or urlparse("http://" + site_url).netloc
    domain = domain.replace("www.", "").split(".")[0]
    return domain.capitalize()

def build_html_body(firma):
    return f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Application</title>
    </head>
    <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6; padding: 20px;">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 6px;">
        <tr>
          <td style="background-color: #004080; color: #fff; padding: 15px; text-align: center; border-radius: 6px 6px 0 0;">
            <h2 style="margin: 0;">Software Engineer Application</h2>
          </td>
        </tr>
        <tr>
          <td style="padding: 20px;">
            <p>Dear <strong>{firma}</strong> Representative,</p>
            <p>
              Please find attached my resume for your kind consideration. I am eager to contribute my skills and experience to a suitable position in your esteemed organization.
            </p>
            <p>
              With my background in software development and project management, I am confident that I can bring valuable contributions to your team.
            </p>
            <p>
              I look forward to hearing from you. Thank you for your time and consideration.
            </p>
            <p style="margin-top: 30px;">
              Best regards,<br>
              <strong>FIRST NAME LAST NAME </strong><br>
              Phone: PHONE NUMBER <br>
              Email: MAİL <br>
              Web Site: WEB SITE 
            </p>
          </td>
        </tr>
        <tr>
          <td style="background-color: #f4f4f4; padding: 10px; font-size: 12px; text-align: center; color: #666; border-radius: 0 0 6px 6px;">
            This email was automatically generated by 
            <a href="https://github.com/dsametkaplan/Automated-HR-Email" style="color: #004080; text-decoration: underline;">
              my application
            </a>.
          </td>
        </tr>
      </table>
    </body>
    </html>
    """

def send_email(receiver_email, subject, html_body, attachment_path):
    msg = EmailMessage()
    msg["From"] = SENDER_EMAIL
    msg["To"] = receiver_email
    msg["Subject"] = subject
    msg.add_alternative(html_body, subtype="html")

    with open(attachment_path, "rb") as f:
        file_data = f.read()
        file_name = attachment_path.split("/")[-1]
        msg.add_attachment(file_data, maintype="application", subtype="pdf", filename=file_name)

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, context=context) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        print(f"test maili gönderildi: {receiver_email}")

def main():
    data = load_sites_from_csv("ik_mailleri.csv")
    if not data:
        print("geçerli site ve e-posta bulunamadı")
        return

    for item in data:
        site = item["site"]
        email = item["email"]
        firma = extract_firma_name(site)
        
        print(f"🌐 Web Sitesi: {site}")
        print(f"🏢 Firma Adı: {firma}")
        print(f"📧 Gönderilecek Mail: {email}")

        receiver_email = email
        subject = "Software Developer Application"
        html_body = build_html_body(firma)
        cv_path = "cv.pdf"
        
        send_email(receiver_email, subject, html_body, cv_path)

if __name__ == "__main__":
    main()
